.travis.yml, src/Zed/ruleset.xml, src/ruleset.xml
Updated ruleset
- exclude generated directory content
- changed minimum priority
Updated travis config
- checks only code style now
Fixed code style
=> core-919 updated rulesets

src/Common/Factory/FactoryNoLogicRule.php, src/Common/ruleset.xml
* Added new FactoryNoLogicRule with priority 2.
** No if-else statements in factory
** No switch-case statements in factory
=> Added new FactoryNoLogicRule with priority 2

src/Zed/Business/Facade/FacadeSingleFactoryCallRule.php, src/Zed/ruleset.xml
* Added new FacadeSingleFactoryCallRule with priority 2.
** Each facade method has to contain no more than one getFactory call
=> Feature: Added FacadeSingleFactoryCallRule

src/Common/ApiInterfaceRule.php, src/Common/Communication/Controller/CommunicationControllerRule.php, src/Common/DependencyProvider/AbstractDependencyProviderRule.php, src/Common/Factory/AbstractFactoryRule.php, src/Common/Factory/FactoryCreateContainOneNewRule.php, src/Common/Factory/FactoryGetContainNoNewRule.php, src/Common/Factory/FactoryMethodReturnInterfaceRule.php, src/Common/Factory/FactoryNoLogicRule.php, src/Common/Factory/FactoryNoLoopsRule.php, src/Common/Factory/FactoryOnlyGetAndCreateRule.php, src/Common/ImplementsApiInterfaceRule.php, src/Common/LayerAccessRule.php, src/Shared/ModuleConstantsNoMethodAllowedRule.php, src/Shared/ModuleConstantsRule.php, src/Zed/Business/Directory/DirectoryNoModelRule.php, src/Zed/Business/Facade/AllMethodsPublicInFacadeRule.php, src/Zed/Business/Facade/FacadeArgumentsRule.php, src/Zed/Business/Facade/FacadeInterfaceRule.php, src/Zed/Business/Facade/FacadeNoLogicRule.php, src/Zed/Business/Facade/FacadeReturnValueRule.php, src/Zed/Business/Facade/FacadeRule.php, src/Zed/Business/Facade/FacadeSingleFactoryCallRule.php, src/Zed/Dependency/Bridge/BridgeConstructorArgumentTypehintsRule.php, src/Zed/Dependency/Bridge/BridgeConstructorArgumentsRule.php
Automatically generated fixes for CodeSniffer errors.
=> Automatically fixed CodeSniffer errors

.gitignore, codeception.yml, src/Zed/Business/Facade/FacadeArgumentsNotAllowedUseEntityTransferRule.php, src/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRule.php, src/Zed/ruleset.xml, tests/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest.php, tests/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest.php, tests/Zed/codeception.yml, tests/_data/Generated/Shared/Transfer/TestModuleEntityTransfer.php, tests/_data/Generated/Shared/Transfer/TestModuleTransfer.php, tests/_data/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest/testFacadeMethodDoesNotHaveEntityTransferArgument.php, tests/_data/Zed/Business/FacadeArgumentsNotAllowedUseEntityTransferRuleTest/testFacadeMethodHasEntityTransferArgument.php, tests/_data/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest/testPluginMethodDoesNotHaveEntityTransferArgument.php, tests/_data/Zed/Communication/Plugin/PluginArgumentsNotAllowedUseEntityTransferRuleTest/testPluginMethodHasEntityTransferArgument.php
Tiket: https://spryker.atlassian.net/browse/DT-199
=> DT-199: RFC: Reduce scope of Entity Transfers

src/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRule.php, src/Zed/ruleset.xml, tests/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest.php, tests/Zed/codeception.yml, tests/_data/Orm/Zed/Persistence/SpyTestEntity.php, tests/_data/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest/testFacadeCanNotCreateSpyEntity.php, tests/_data/Zed/Persistence/Repository/RepositoryCanUseSpyEntityRuleTest/testRepositoryCanCreateSpyEntity.php
Tiket: https://spryker.atlassian.net/browse/DT-200
=> DT-200: Implemented RFC - Repository for Persistence Layer

src/Common/Plugin/AbstractPluginRule.php, src/Common/Plugin/NewPluginExtensionModuleRule.php, src/Common/ruleset.xml, src/SprykerAbstractRule.php, tests/Common/Plugin/NewPluginExtensionModuleTest.php, tests/_bootstrap.php, tests/_data/Common/Plugin/NewPluginExtensionModuleTest/testRuleAppliesWhenPluginImplementsNotExtensionModuleInterface.php, tests/_data/Common/Plugin/NewPluginExtensionModuleTest/testRuleDoesNotApplyWhenPluginImplementsExtensionModuleInterface.php
- Ticket: https://spryker.atlassian.net/browse/DT-196
=> [DT-196] check RFC: Extension modules on new plugin creation

src/Common/ruleset.xml
- Jira ticket: https://spryker.atlassian.net/browse/GLUE-5088
=> GLUE-5088 Bridge method names do not fit original facade method names

src/Common/Bridge/BridgeNameRule.php
- Developer(s): @gerner-spryker  
- Ticket: https://spryker.atlassian.net/browse/DT-905
- Release Group: https://release.spryker.com/release-groups/view/1254
ArchitectureSniffer           | patch {skip}                 |                      |
Fixed error messages for bridge name rule.
=> DT-905: Fixing error messages for bridge name rule

composer.json, src/Path/PathBuilder.php, src/PropelQuery/PropelQueryFactory.php, src/PropelQuery/Schema/PropelSchemaTableFinder.php
- Developer(s): @romanhavrylko
- Ticket: https://spryker.atlassian.net/browse/TE-7666
ArchitectureSniffer           | patch {skip}                |               |
=> TE-7819 Replaced Zend usage

.travis.yml, README.md, composer.json, src/Path/PathBuilder.php, src/PropelQuery/PropelQueryFactory.php, src/PropelQuery/Schema/PropelSchemaTableFinder.php
- Developer(s): @romanhavrylko
- Ticket: https://spryker.atlassian.net/browse/TE-7664
ArchitectureSniffer           | patch       |   Laminas            |
-----------------------------------------
Improvements
- Replaced Zend dependency with Laminas module.
=> TE 7664 Replaced Zend usage

.github/workflows/ci.yml, .gitignore
=> TE-7900 Updated tests.

.github/workflows/ci.yml, README.md
=> Added coverage.

src/Zed/Dependency/Bridge/AbstractBridgeRule.php, src/Zed/Dependency/Bridge/BridgeClassNamingRule.php, src/Zed/Dependency/Bridge/BridgeInterfaceNamingConventionRule.php, tests/Zed/Dependency/Bridge/BridgeClassNamingRuleTest.php, tests/Zed/Dependency/Bridge/BridgeInterfaceNamingConventionRuleTest.php, tests/Zed/codeception.yml, tests/_data/Zed/Dependency/Bridge/BridgeClassNamingRuleTest/testBridgeClassNameDoesMatch.php, tests/_data/Zed/Dependency/Bridge/BridgeClassNamingRuleTest/testBridgeClassNameDoesNotMatch.php, tests/_data/Zed/Dependency/Bridge/BridgeInterfaceNamingConventionRuleTest/testBridgeNamingConventionDoesMatch.php, tests/_data/Zed/Dependency/Bridge/BridgeInterfaceNamingConventionRuleTest/testBridgeNamingConventionDoesNotMatch.php
=> Adding bridge related rules

.github/workflows/ci.yml, composer.json, src/Node/Reader/NodeReader.php, src/Node/Reader/NodeReaderInterface.php, src/PropelQuery/ClassNode/Transfer/ClassNodeTransfer.php, src/PropelQuery/Module/ModuleFinder.php, src/PropelQuery/PropelQueryFacade.php, src/PropelQuery/PropelQueryFacadeInterface.php, src/PropelQuery/PropelQueryFactory.php, src/PropelQuery/Query/QueryFinder.php, src/PropelQuery/Query/QueryFinderInterface.php, src/PropelQuery/Relation/RelationFinder.php, src/PropelQuery/Relation/RelationFinderInterface.php, tests/AbstractArchitectureSnifferRuleTest.php
https://spryker.atlassian.net/browse/TE-9771
Will need a new patch release, but for now is core only.
I will also ignore the newly added and failing prefer lowest for now
=> Allow testing PHP 8

composer.json
=> prefer-lowest

composer.json
- Developer(s): @dmytro-dymarchuk 
- Ticket: https://spryker.atlassian.net/browse/TE-10992
- Release Group: https://release.spryker.com/release-groups/view/4090
- merge: merge
ArchitectureSniffer   | patch (currently 0.x)  |                       |
-----------------------------------------
Improvements
- Removed `ondrejmirtes/better-reflection` from dependencies.
=> Remove ondrejmirtes/better-reflection from dependencies

.github/workflows/ci.yml, README.md, composer.json
=> FRW-332 Drop PHP7 and Symfony v4

composer.json
Found a missing dependency to be the issue here.
=> Fix PHPStan / Library dependency

.github/workflows/ci.yml, composer.json
- Developer(s): @geega 
- Ticket: https://spryker.atlassian.net/browse/FRW-19
- Release Group: https://release.spryker.com/release-groups/view/4549
- merge: merge
ArchitectureSniffer   | patch (currently 0.x)  |                       |
-----------------------------------------
- Adjusted `composer.json` to allow for new `symfony/finder:^6.0.0` major.
=> FRW-19 Support Symfony packages v6.

.github/workflows/ci.yml
=> Removed composer validate lowest check from CI

.github/workflows/ci.yml, README.md, composer.json
https://spryker.atlassian.net/browse/FRW-998
=> FRW-998 Dropped PHP 7.4 support.
